#!/bin/bash -x

#replace parameters
sed -i 's/__HOSTNAME__/'"$(hostname -I)"'/g' /etc/confd/templates/elasticsearch.tmpl

#replace bucketname with env vairable
sed -i 's/_ELASTICSEARCH_BUCKET_/'"$ELASTICSEARCH_BUCKET"'/g' /etc/confd/conf.d/*.toml

#restart confd to reflect new conf.d files
sudo /etc/init.d/fk-config-service-confd restart

#set proper permissions
chown -R elasticsearch:elasticsearch /var/log/elasticsearch
chown -R elasticsearch:elasticsearch /etc/elasticsearch
chown -R root:elasticsearch /etc/init.d/elasticsearch
chown -R elasticsearch:elasticsearch /var/lib/elasticsearch 
chown -R root:elasticsearch /etc/default/elasticsearch 
#install the basic plugins useful for all

